name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: install dependencies
        run: pnpm install
      - name: transpile typescript
        run: pnpm run build
      # - name: run tests
      #   run: pnpm run test
